spring:
  application:
    name: OnlineStore
  datasource:
    url: jdbc:mysql://${RDS_URL}/fashion_store?useSSL=false
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddlAuto: none
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
server:
  port: 0
